/* Copyright 2021 Valdimar Björn Ásgeirsson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#include QMK_KEYBOARD_H

enum my_layers {
    // clang-format off
    _QWERTY,
    _HALMAK,
    _LOWER,
    _UPPER
    // clang-format on
    };

// Layer toggling behavior definitions
#define HALMAK TG(_HALMAK)
#define LOWER MO(_LOWER)
#define UPPER MO(_UPPER)

// Control when held, Escape when tapped
#define CT_ESC LCTL_T(KC_ESC)

// I use Hammerspoon scripts with ctrl-alt and hyper for window management
#define CALT LCTL(KC_LALT)
#define HYPER LCTL(LALT(KC_LGUI))  // Hyper key modifier defined as CTRL+ALT+SUPER

// Firefox tab navigation
#define FF_L LGUI(LALT(KC_LEFT))
#define FF_R LGUI(LALT(KC_RIGHT))

// =================================
//     KEYMAP DEFINITIONS
// =================================
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // clang-format off

/* Base (QWERTY)
 *                   ,-------------------------------. ,-------------------------------.
 * ,-----------------|   W   |   E   |   R   |   T   | |   Y   |   U   |   I   |   O   |-----------------.
 * |   TAB   |   Q   |-------+-------+-------+-------| |-------+-------+-------+-------|   P   |  LBRC   |
 * |---------+-------|   S   |   D   |   F   |   G   | |   H   |   J   |   K   |   L   |-------+---------|
 * | CT_ESC  |   A   |-------+-------+-------+-------| |-------+-------+-------+-------| SCLN  |  QUOT   |
 * |---------+-------|   X   |   C   |   V   |   B   | |   N   |   M   | COMM  |  DOT  |-------+---------|
 * |  LSFT   |   Z   |-------+-------+---------------' `---------------+-------+-------| SLSH  | BSLASH  |
 * |---------+-------| LBRC  | RBRC  |                                 | MINS  |  EQL  |-------+---------|
 * |  UPPER  | HYPER |---------------'                                 `---------------| RSFT  |  LOWER  |
 * `-----------------'       ,-----------------------. ,-----------------------.       `-----------------'
 *                           | LGUI  |  SPC  | BSPC  | |  TAB  |  ENT  |  GRV  |
 *                           |-------|       |       | |       |       |-------|
 *                           | CALT  |-------+-------| |-------+-------|CT_ESC |
 *                           `-------| LOWER | LALT  | | RALT  | UPPER |-------'
 *                                   `---------------' `---------------'       generated by [keymapviz] */
[_QWERTY] = LAYOUT( \
    KC_TAB,  KC_Q,  KC_W,   KC_E,   KC_R, KC_T,             KC_Y, KC_U, KC_I,    KC_O,   KC_P,    KC_LBRC,   \
    CT_ESC,  KC_A,  KC_S,   KC_D,   KC_F, KC_G,             KC_H, KC_J, KC_K,    KC_L,   KC_SCLN, KC_QUOT,   \
    KC_LSFT, KC_Z,  KC_X,   KC_C,   KC_V, KC_B,             KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_BSLASH, \
    UPPER,   HYPER, KC_LBRC, KC_RBRC,                                   KC_MINS, KC_EQL, KC_RSFT, LOWER,     \
                        KC_LGUI, KC_SPC, KC_BSPC,         KC_TAB, KC_ENT, KC_GRV,                            \
                        CALT,    LOWER,  KC_LALT,         KC_RALT, UPPER, CT_ESC                             \
),

/* HALMAK (toggle via UPPER)
 *                   ,-------------------------------. ,-------------------------------.
 * ,-----------------|   L   |   R   |   B   |   Z   | | SCLN  |   Q   |   U   |   D   |-----------------.
 * |         |   W   |-------+-------+-------+-------| |-------+-------+-------+-------|   J   |         |
 * |---------+-------|   H   |   N   |   T   | COMM  | |  DOT  |   A   |   E   |   O   |-------+---------|
 * |         |   S   |-------+-------+-------+-------| |-------+-------+-------+-------|   I   |         |
 * |---------+-------|   M   |   V   |   C   | SLSH  | |   G   |   P   |   X   |   K   |-------+---------|
 * |         |   F   |-------+-------+---------------' `---------------+-------+-------|   Y   |         |
 * |---------+-------|       |       |                                 |       |       |-------+---------|
 * |         |       |---------------'                                 `---------------|       |         |
 * `-----------------'       ,-----------------------. ,-----------------------.       `-----------------'
 *                           |       |       |       | |       |       |       |
 *                           |-------|       |       | |       |       |-------|
 *                           |       |-------+-------| |-------+-------|       |
 *                           `-------|       |       | |       |       |-------'
 *                                   `---------------' `---------------'       generated by [keymapviz] */

[_HALMAK] = LAYOUT( \
    _______, KC_W, KC_L, KC_R, KC_B, KC_Z,                  KC_SCLN, KC_Q,  KC_U, KC_D, KC_J, _______,   \
    _______, KC_S, KC_H, KC_N, KC_T, KC_COMM,               KC_DOT,  KC_A,  KC_E, KC_O, KC_I, _______,   \
    _______, KC_F, KC_M, KC_V, KC_C, KC_SLSH,               KC_G,    KC_P,  KC_X, KC_K, KC_Y, _______,   \
    _______,_______,_______,_______,                                  _______,_______,_______,_______,   \
                            _______,_______,_______,            _______,_______,_______,                 \
                            _______,_______,_______,            _______,_______,_______                  \
),

/* Lower layer: Numbers and symbols
 *                   ,-------------------------------. ,-------------------------------.
 * ,-----------------|S(KC_7)|S(KC_8)|S(KC_9)|S(KC_LB| |S(KC_RB|  P7   |  P8   |  P9   |-----------------.
 * |  RESET  |       |-------+-------+-------+-------| |-------+-------+-------+-------| PLUS  |  HOME   |
 * |---------+-------|S(KC_4)|S(KC_5)|S(KC_6)| LPRN  | | RPRN  |  P4   |  P5   |  P6   |-------+---------|
 * |         |       |-------+-------+-------+-------| |-------+-------+-------+-------| MINS  |   END   |
 * |---------+-------|S(KC_1)|S(KC_2)|S(KC_3)| LBRC  | | RBRC  |  P1   |  P2   |  P3   |-------+---------|
 * |  PSCR   |       |-------+-------+---------------' `---------------+-------+-------|  EQL  |  PGUP   |
 * |---------+-------|       |S(KC_0)|                                 |  P0   | PIPE  |-------+---------|
 * |         |       |---------------'                                 `---------------| UNDS  |  PGDN   |
 * `-----------------'       ,-----------------------. ,-----------------------.       `-----------------'
 *                           |       |       |       | |       |       |       |
 *                           |-------|       |       | |       |       |-------|
 *                           |       |-------+-------| |-------+-------|       |
 *                           `-------|       |       | |       |       |-------'
 *                                   `---------------' `---------------'       generated by [keymapviz] */
[_LOWER] = LAYOUT(
    RESET,  _______, S(KC_7), S(KC_8),  S(KC_9), S(KC_LBRC),      S(KC_RBRC), KC_P7, KC_P8,  KC_P9, KC_PLUS, KC_HOME, \
    _______,_______, S(KC_4), S(KC_5),  S(KC_6), KC_LPRN,            KC_RPRN, KC_P4, KC_P5,  KC_P6, KC_MINS, KC_END,  \
    KC_PSCR,_______, S(KC_1), S(KC_2),  S(KC_3), KC_LBRC,            KC_RBRC, KC_P1, KC_P2,  KC_P3, KC_EQL,  KC_PGUP, \
    _______,_______,_______, S(KC_0),                                                KC_P0,KC_PIPE, KC_UNDS, KC_PGDN, \
                            _______,_______,_______,            _______,_______,_______,                              \
                            _______,_______,_______,            _______,_______,_______                               \
),

/* Upper: OS & function keys
 *                   ,-------------------------------. ,-------------------------------.
 * ,-----------------|  F1   |  F2   |  F3   |  F4   | | FF_L  | FF_R  | NLCK  |  INS  |-----------------.
 * |  PAUS   | RESET |-------+-------+-------+-------| |-------+-------+-------+-------|       |  VOLU   |
 * |---------+-------|  F5   |  F6   |  F7   |  F8   | | LEFT  | DOWN  |  UP   | RGHT  |-------+---------|
 * |  SLCK   |       |-------+-------+-------+-------| |-------+-------+-------+-------|       |  VOLD   |
 * |---------+-------|  F9   |  F10  |  F11  |  F12  | | MS_L  | MS_D  | MS_U  | MS_R  |-------+---------|
 * |         |       |-------+-------+---------------' `---------------+-------+-------|       |  MUTE   |
 * |---------+-------|       |HALMAK |                                 | MPRV  | MPLY  |-------+---------|
 * |         |       |---------------'                                 `---------------| MNXT  |         |
 * `-----------------'       ,-----------------------. ,-----------------------.       `-----------------'
 *                           | BTN3  | BTN1  | BTN2  | | ACL0  | ACL1  | ACL2  |
 *                           |-------|       |       | |       |       |-------|
 *                           | BTN4  |-------+-------| |-------+-------|       |
 *                           `-------|       |       | |       |       |-------'
 *                                   `---------------' `---------------'       generated by [keymapviz] */
[_UPPER] = LAYOUT(
    KC_PAUS,RESET,  KC_F1, KC_F2,  KC_F3,  KC_F4,             FF_L,    FF_R,    KC_NLCK,KC_INS, _______,KC_VOLU, \
    KC_SLCK,_______,KC_F5, KC_F6,  KC_F7,  KC_F8,             KC_LEFT, KC_DOWN, KC_UP,  KC_RGHT,_______,KC_VOLD, \
    _______,_______,KC_F9, KC_F10, KC_F11, KC_F12,            KC_MS_L, KC_MS_D, KC_MS_U,KC_MS_R,_______,KC_MUTE, \
    _______,_______,_______,HALMAK,                                             KC_MPRV,KC_MPLY,KC_MNXT,_______, \
                            KC_BTN3,KC_BTN1,KC_BTN2,        KC_ACL0,KC_ACL1,KC_ACL2,                             \
                            KC_BTN4,_______,_______,        _______, _______, _______                            \
)
};
// clang-format on

void persistent_default_layer_set(uint16_t default_layer) {
    eeconfig_update_default_layer(default_layer);
    default_layer_set(default_layer);
}
